version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    image: nodejs-amq-publisher/app
    container_name: app
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - PORT=3000
      - AMQ_TOPIC_NAME=/topic/publish
      - AMQ_BROKER_URL=ws://activemq:61614
    depends_on:
      - activemq

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: nodejs-amq-publisher/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - '8080:80'
    depends_on:
      - app
    networks:
      - app-network

  activemq:
    image: 'rmohr/activemq:5.15.9-alpine'
    container_name: activemq
    restart: unless-stopped
    ports:
      - '61614:61614'
      - '8161:8161'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
