version: "3"

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    image: example/app
    container_name: app
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - PORT=3000

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: example/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
